# Generated by Django 4.0.5 on 2022-11-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.JSONField(null=True),
        ),
    ]
