# Generated by Django 4.0.5 on 2022-11-30 21:54

from django.db import migrations, models
import play2learn.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_applicant_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs only', storage=play2learn.storage_backends.PrivateMediaStorage(), upload_to='resumes'),
        ),
    ]
