# Generated by Django 4.0.5 on 2022-11-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_applicant_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(blank=True, choices=[('Day', 'Monday'), ('Day', 'Tuesday'), ('Day', 'Wednesday'), ('Day', 'Thursday'), ('Day', 'Friday')], max_length=150),
        ),
    ]
