# Generated by Django 4.0.5 on 2022-11-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_applicant_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], max_length=150),
        ),
    ]
