# Generated by Django 4.0.5 on 2022-11-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_applicant_available_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.TextField(),
        ),
    ]
