# Generated by Django 4.0.5 on 2022-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_applicant_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(),
        ),
    ]
