# Generated by Django 4.0.5 on 2022-06-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=120),
        ),
    ]
