# Generated by Django 4.0.5 on 2022-10-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_remove_title_user'),
        ('reviews', '0003_remove_review_one_review_per_user_per_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.title'),
        ),
    ]
