# Generated by Django 4.0.5 on 2022-10-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_one_review_per_user_per_game_title_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='review',
        #     name='one_review_per_user_per_title',
        # ),
        # migrations.AddConstraint(
        #     model_name='review',
        #     constraint=models.UniqueConstraint(fields=('user', 'game_title'), name='one_review_per_user_per_game'),
        # ),
    ]
