# Generated by Django 4.0.5 on 2022-10-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='user_name',
            new_name='user',
        ),
    ]
