# Generated by Django 4.0.5 on 2022-10-18 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0002_rename_user_name_gamescore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='play', to=settings.AUTH_USER_MODEL),
        ),
    ]
