# Generated by Django 4.0.5 on 2022-10-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_alter_gamescore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='user',
            field=models.TextField(),
        ),
    ]
