# Generated by Django 4.0.5 on 2022-10-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_alter_gamescore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='user',
        ),
    ]
