# Generated by Django 4.0.5 on 2022-10-18 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_delete_gamescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0007_remove_gamescore_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='play', to='games.title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='play', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
