# Generated by Django 4.0.5 on 2022-10-18 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0015_delete_gamescore'),
        ('play', '0009_remove_gamescore_title_remove_gamescore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='play', to='games.title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='play', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
