# Generated by Django 4.0.5 on 2022-10-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_gamescore_title_gamescore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='word_length',
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
