# Generated by Django 4.0.5 on 2022-10-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0013_alter_gamescore_score_alter_gamescore_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('Math Facts', 'Math Facts'), ('Anagram Hunt', 'Anagram Hunt')], default='Math Facts'),
        ),
    ]
