# Generated by Django 4.0.5 on 2022-10-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_delete_gamescore'),
        ('play', '0014_alter_gamescore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='games.game'),
        ),
    ]
