# Generated by Django 4.0.5 on 2022-10-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_alter_gamescore_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='title',
            new_name='game_title',
        ),
    ]
