# Generated by Django 4.0.5 on 2022-10-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_delete_gamescore'),
        ('play', '0016_rename_title_gamescore_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='games.title'),
        ),
    ]
