# Generated by Django 4.0.5 on 2022-10-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0017_alter_gamescore_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='game_title',
            new_name='title',
        ),
    ]
