# Generated by Django 4.0.5 on 2022-10-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_delete_gamescore'),
        ('play', '0018_rename_game_title_gamescore_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='title',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='game_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='play', to='games.game'),
            preserve_default=False,
        ),
    ]
