# Generated by Django 4.0.5 on 2022-10-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0022_rename_game_gamescore_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
