# Generated by Django 4.0.5 on 2022-06-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_review_one_review_per_user_per_game_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
