# Generated by Django 4.0.5 on 2022-06-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_word_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
    ]
