# Generated by Django 4.0.5 on 2022-06-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
