# Generated by Django 4.0.5 on 2022-06-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='slug',
        ),
    ]
