# Generated by Django 4.0.5 on 2022-06-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
