# Generated by Django 4.0.5 on 2022-06-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='timestamp',
            field=models.DateTimeField(default='2022-06-10 10:45'),
            preserve_default=False,
        ),
    ]
