# Generated by Django 4.0.5 on 2022-06-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_contactus_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.title'),
            preserve_default=False,
        ),
    ]
