# Generated by Django 4.0.5 on 2022-06-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_number',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='operation',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='word_length',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
