# Generated by Django 4.0.5 on 2022-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_game_max_number_alter_game_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
