# Generated by Django 4.0.5 on 2022-10-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_contactus_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('game', models.TextField(choices=[('MATH', 'Math Game'), ('ANAGRAM', 'Anagram Game')], default='MATH')),
                ('score', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
