# Generated by Django 4.0.5 on 2022-10-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamescore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
