# Generated by Django 4.0.5 on 2022-10-18 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0015_delete_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('word_length', models.SmallIntegerField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('game_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_anagram', to='games.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_anagram', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaderboard',
            },
        ),
    ]
