# Generated by Django 4.0.5 on 2022-10-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_gameanagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanagram',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
