# Generated by Django 4.0.5 on 2022-10-18 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0018_alter_gameanagram_game_title_alter_gameanagram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='game', to=settings.AUTH_USER_MODEL),
        ),
    ]
