# Generated by Django 4.0.5 on 2022-10-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_alter_game_game_title_alter_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.TextField(choices=[('Math Facts', 'Math Facts'), ('Anagram Hunt', 'Anagram Hunt')], default='Math Facts'),
        ),
    ]
