# Generated by Django 4.0.5 on 2022-10-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_alter_game_timestamp_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanagram',
            name='title',
            field=models.TextField(choices=[('Math Facts', 'Math Facts'), ('Anagram Hunt', 'Anagram Hunt')], default='Math Facts'),
        ),
    ]
