# Generated by Django 4.0.5 on 2022-10-19 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0022_gameanagram_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanagram',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gameanagram', to=settings.AUTH_USER_MODEL),
        ),
    ]
