# Generated by Django 4.0.5 on 2022-10-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0023_alter_gameanagram_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['game_title'], 'verbose_name_plural': 'Titles'},
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='game_title',
        ),
        migrations.AlterField(
            model_name='title',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='game_title', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GameAnagram',
        ),
    ]
