# Generated by Django 4.0.5 on 2022-10-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_alter_title_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
    ]
