# Generated by Django 4.0.5 on 2022-11-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_alter_game_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
