# Generated by Django 4.0.5 on 2022-11-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_alter_contactus_timestamp_alter_game_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
