# Generated by Django 4.0.5 on 2022-12-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_contactus_first_name_contactus_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
    ]
